apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: postgres-db-sfs
spec:
  serviceName: "postgres-db-sfs"
  replicas: 1
  selector:
    matchLabels:
      app: postgresql
  template:
    metadata:
      labels:
        app: postgresql
    spec:
      containers:
      - name: postgresql
        image: postgres:latest
        env:
        - name: POSTGRES_DB
          value: todo_app
        - name: POSTGRES_PASSWORD
          valueFrom:
            secretKeyRef:
              name: postgres-password-secret
              key: postgres-password
        ports:
        - containerPort: 5432
#        volumeMounts:
#        - name: my-postgres-data
#          mountPath: /var/lib/postgresql/data
  volumeClaimTemplates:
  - metadata:
      name: my-postgres-data
    spec:
      accessModes: [ "ReadWriteOnce" ]
      resources:
        requests:
          storage: 5Gi
